export const QuestionActionTypes={
    SET_FETCHED_QUESTIONS_TO_STATE_Xenatus2:'SET_FETCHED_QUESTIONS_TO_STATE_Xenatus2',
    SET_SELECTED_QUESTION_Xenatus2:'SET_SELECTED_QUESTION_Xenatus2',
    SELECTED_QUESTION_NEXT_Xenatus2:'SELECTED_QUESTION_NEXT_Xenatus2',
    SELECTED_QUESTION_PREVIOUS_Xenatus2:'SELECTED_QUESTION_PREVIOUS_Xenatus2',
    SET_SELECTED_ANSWER_Xenatus2:'SET_SELECTED_ANSWER_Xenatus2',
    // SET_RECENT_FETCHED_TIME:"SET_RECENT_FETCHED_TIME"
}